name: Build and Push

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Dependencies
      run: npm install
    - name: Build Files
      run: npm run build
    - name: put to Linode bucket
      run: |
        sudo apt-get install s3cmd
        s3cmd put --recursive dist s3://accessu2020/test/ --host=us-east-1.linodeobjects.com --secret_key=${{ secrets.LINODE_SECRET_KEY }} --access_key=${{ secrets.LINODE_ACCESS_KEY }}
        s3cmd ws-create --ws-index=index.html s3://accessu2020/test/ --host=us-east-1.linodeobjects.com --secret_key=${{ secrets.LINODE_SECRET_KEY }} --access_key=${{ secrets.LINODE_ACCESS_KEY }}
      
