name: Build and Push

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Dependencies
      run: npm install
    - name: Build Files
      run: npm run build
    - name: put to Linode bucket
      run: |
        sudo apt-get install s3cmd
        echo "[default]" > /home/runner/.s3cfg
        echo "access_key = ${{ secrets.LINODE_ACCESS_KEY }}" >> /home/runner/.s3cfg
        echo "secret_key = ${{ secrets.LINODE_SECRET_KEY }}" >> /home/runner/.s3cfg
        echo "bucket_location = US" >> /home/runner/.s3cfg
        echo "host_base = us-east-1.linodeobjects.com" >> /home/runner/.s3cfg
        s3cmd put --recursive dist/* s3://accessu2020/test/ -P
      
